[project]
name = "flathub-stats"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argparse>=1.4.0",
    "pygobject==3.52.3",
]

[dependency-groups]
dev = [
    "faker>=37.0.0",
    "ruff>=0.11.0",
]
